export type Result = { id: string; rank: number; playerName: string; teamName: string; durationMs: number; formattedTime: string; displayLabel: string; rpm?: number; displayRpmLabel?: string; imageUrl?: string };
export type ActiveAttempt = { playerId: string; playerName: string; teamName?: string; startedAt: string; elapsedMsAtSnapshot: number };
export type Snapshot = { schemaVersion: 1; generatedAt: string; sourceFetchedAt: string; currentHeat: { id: string; number: number; year: number; date: string; state: "running" | "completed" | "unknown" }; activities: { beer: { completed: Result[]; active: ActiveAttempt[]; attemptsStarted: number; attemptsCompleted: number }; spin: { completed: Result[]; active: ActiveAttempt[]; attemptsStarted: number; attemptsCompleted: number }; sail: { teams: Array<{ teamId: string; teamName: string; imageUrl?: string; sailLogCount: number; handoffCount: number; completedLegCount: number; status: "racing" | "finished" | "unknown"; currentPlayerName?: string; startedAt: string; elapsedMsAtSnapshot: number; finishedAt?: string }> } } };
const object = (value: unknown): Record<string, unknown> => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Unsupported snapshot: expected object"); return value as Record<string, unknown>; };
const array = (value: unknown): unknown[] => Array.isArray(value) ? value : (() => { throw new Error("Unsupported snapshot: expected array"); })();
const result = (value: unknown): void => { const item = object(value); if (typeof item.id !== "string" || typeof item.rank !== "number" || typeof item.playerName !== "string" || typeof item.teamName !== "string" || typeof item.durationMs !== "number" || typeof item.formattedTime !== "string" || typeof item.displayLabel !== "string") throw new Error("Unsupported snapshot: invalid result"); };
const active = (value: unknown): void => { const item = object(value); if (typeof item.playerId !== "string" || typeof item.playerName !== "string" || typeof item.startedAt !== "string" || typeof item.elapsedMsAtSnapshot !== "number") throw new Error("Unsupported snapshot: invalid active attempt"); };
const sailTeam = (value: unknown): void => { const item = object(value); if (typeof item.teamId !== "string" || typeof item.teamName !== "string" || typeof item.sailLogCount !== "number" || typeof item.handoffCount !== "number" || typeof item.completedLegCount !== "number" || typeof item.startedAt !== "string" || typeof item.elapsedMsAtSnapshot !== "number" || !["racing", "finished", "unknown"].includes(String(item.status))) throw new Error("Unsupported snapshot: invalid sail team"); };
export function parseCurrentHeatSnapshot(value: unknown): Snapshot {
  const root = object(value); if (root.schemaVersion !== 1) throw new Error("Unsupported snapshot schemaVersion");
  const heat = object(root.currentHeat); const activities = object(root.activities); const sail = object(activities.sail);
  if (typeof heat.id !== "string" || typeof heat.number !== "number" || typeof heat.year !== "number" || typeof root.generatedAt !== "string" || typeof root.sourceFetchedAt !== "string") throw new Error("Unsupported snapshot: invalid heat metadata");
  for (const name of ["beer", "spin"] as const) { const activity = object(activities[name]); const completed = array(activity.completed); const inProgress = array(activity.active); completed.forEach(result); inProgress.forEach(active); if (typeof activity.attemptsStarted !== "number" || typeof activity.attemptsCompleted !== "number") throw new Error("Unsupported snapshot: invalid activity"); }
  array(sail.teams).forEach(sailTeam); return root as unknown as Snapshot;
}
export function sailSlots(count: number, target = 16): boolean[] { const completed = Math.max(0, Math.min(target, Math.floor(count))); return Array.from({ length: target }, (_, index) => index < completed); }
export function isStaleSnapshot(generatedAt: string, now = new Date()): boolean { const published = Date.parse(generatedAt); return !Number.isFinite(published) || now.getTime() - published > 7 * 60_000; }
